// Action Constants
export const TOGGLE_DB_MODAL = 'TOGGLE_DB_MODAL';
export const SAVE_DB_NAME = 'SAVE_DB_NAME';
export const TOGGLE_TABLE_MODAL = 'TOGGLE_TABLE_MODAL';
export const SAVE_TABLE = 'SAVE_TABLE';
export const REMOVE_TABLE = 'REMOVE_TABLE';
export const ENABLE_TABLE_EDIT = 'ENABLE_TABLE_EDIT';
export const UPDATE_TABLE = 'UPDATE_TABLE';
export const TOGGLE_COLUMN_MODAL = 'TOGGLE_COLUMN_MODAL';
export const SAVE_COLUMN = 'SAVE_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const ENABLE_COLUMN_EDIT = 'ENABLE_COLUMN_EDIT';
export const UPDATE_COLUMN = 'UPDATE_COLUMN';
export const SAVE_FOREIGN_KEY_RELATION = 'SAVE_FOREIGN_KEY_RELATION';
export const UPDATE_FOREIGN_KEY_RELATION = 'UPDATE_FOREIGN_KEY_RELATION';
export const STORE_TABLE_POSITION = 'STORE_TABLE_POSITION';
